name: React CI

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs: 
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      working-directory: frontend
      run: npm install

    # - name: Run Tests
    #   working-directory: frontend
    #   run: npm test   
    
    - name: Build Project
      working-directory: frontend
      run: npm run build

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

  deploy_staging:
   needs: build
   runs-on: ubuntu-latest
   steps:
    # - name: Checkout code
    #   uses: actions/checkout@v3
    
    # - name: Install Vercel CLI
    #   run: npm install -g vercel

    # - name: Deploy to vercel
    #   run: vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }} \
    #               --scope \
    #               --project test-react-app  
    #   working-directory: frontend 

    - name: Slack Notification
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text": "Deployment to *${{ github.ref_name }}* branch is complete!"}' \
        ${{ secrets.SLACK_WEBHOOK_URL }}